apiVersion: apps/v1
kind: Deployment
metadata:
  name: koldstedev
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koldstedev
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: koldstedev
    spec:
      containers:
        # - image: <set in the azure pipeline>
        securityContext: # https://techcommunity.microsoft.com/t5/microsoft-developer-community/hardening-an-asp-net-container-running-on-kubernetes/ba-p/2542224
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 2000
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
              
        name: koldstedev
        ports:
          - containerPort: 8800
            name: http
