apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: koldstedev
  namespace: backend
spec:
  ports:
    - name: https
      port: 80
      targetPort: 8800
  selector:
    app: koldstedev
