# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

### THIS PIPELINE RUNS THIRD AND AFTER THE "CI_playwright-azure-pipeline" PIPELINE ###
trigger: none # Trigger is located at the bottom of this pipeline.

resources:
- repo: self

variables:
- group: Container-Registry-do

stages: 
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build, push and publish artifact
    pool:
      vmImage: ubuntu-latest
    steps:

    # To lower the risk of an active garbage collection starting between the garbage collection check and the push,
    # build and push are not part of the same task, and seperated by a garbage collection check.
    - task: Docker@2
      displayName: 'Building Docker image'
      inputs:
        containerRegistry: '$(containerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: '$(tag)'
        arguments: '--build-arg ASPNETCORE_HTTP_PORTS=8800'

    # Imaged can't be pushed when there is an active garbage collection running, 
    # this will not let the push happen until after the garbage collection is finished, if there is one.
    - task: Bash@3
      displayName: 'Waits for the garbage collection to be done, if necessary'
      inputs:
        filePath: 'Azure-Pipelines/Bash Scripts/Image Push Retention - Wait For The Garbage Collection To Be Done.sh'
        failOnStderr: true
      env:
        bearerTokenContainerRegistry: $(bearerTokenContainerRegistry)
        containerRegistryAPIBaseURL: $(containerRegistryAPIBaseURL)

    - task: Docker@2
      displayName: 'Pushing the image to the container registry'
      inputs:
        containerRegistry: $(containerRegistryServiceConnection)
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

    - script: |
        # Uncomments the image property.
        sed -i "s|# image:|image:|" $(System.DefaultWorkingDirectory)/Koldste.dev.Web/Manifests/website-koldstedev/Deployment_koldstedev.yaml

        # Sets the name of the image property.
        sed -i "s|{{DOCKER_IMAGE_NAME}}|$(containerRegistryURL)/$(imageRepository)|g" $(System.DefaultWorkingDirectory)/Koldste.dev.Web/Manifests/website-koldstedev/Deployment_koldstedev.yaml

        # Replaces the imager property value's placeholder.
        sed -i "s|{{DOCKER_IMAGE_TAG}}|latest|" $(System.DefaultWorkingDirectory)/Koldste.dev.Web/Manifests/website-koldstedev/Deployment_koldstedev.yaml
      displayName: 'Replace Docker image name and tag in deployment manifest file'
        
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/Koldste.dev.Web/Manifests'
        artifact: 'Manifests'
        publishLocation: 'pipeline'


    - script: |
        echo $(System.AccessToken) | az devops login

        az pipelines run --name CD_Docker-Deploy-pipeline --branch pipeline_env

        az devops logout
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'pipeline_env'))
      displayName: 'Trigger for CD_Docker-Deploy-pipeline'
