# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

### THIS PIPELINE RUNS SECOND AND AFTER THE "CI_.NET-azure-pipeline" PIPELINE ###
resources:

  repositories:
  - repository: repo
    type: git
    name: CV_Portfolio-Hjemmeside
    ref: self
    
  pipelines:
  - pipeline: CIDotNETazurepipeline
    source: CI_.NET-azure-pipeline
    trigger: true

variables:
- group: Container-Registry-do

stages:
- stage: Build
  displayName: Building Docker image
  jobs:
  - job: Build
    displayName: Build Docker image
    pool:
      vmImage: ubuntu-latest
    steps:

    # Build and push are not part of the same task, and seperated by a garbage collection check,
    # to lower the chanch of an active garbage collection starting between the garbage collection check and the push.
    - task: Docker@2
      displayName: 'Building Docker image'
      inputs:
        containerRegistry: 'azure_pipeline/DigitalOcean-ContainerRegistry/koldste.dev'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: '$(tag)'

- stage: Push
  displayName: Pushing Docker image to the container registry
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - job: Push
    displayName: Push image and publish artifact
    pool:
      vmImage: ubuntu-latest
    steps:
    # Imaged can't be pushed when there is an active garbage collection running, 
    # this will not let the push happen until after the garbage collection is finished, if there is one.
    - task: Bash@3
      displayName: 'Waits for the garbage collection to be done, if necessary'
      inputs:
        filePath: 'Azure-Pipelines/Bash Scripts/Image Push Retention - Wait For The Garbage Collection To Be Done'
        failOnStderr: true

    - task: Docker@2
      displayName: 'Pushing the image to the container registry'
      inputs:
        containerRegistry: 'azure_pipeline/DigitalOcean-ContainerRegistry/koldste.dev'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

    - script: |
        docker images
      displayName: 'List Docker images'
        
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'Koldste.dev.Web/Manifests'
        artifact: 'Manifests'
        publishLocation: 'pipeline'