# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- group: Container-Registry-do
- name: containerRegistryServiceConnection
  value: 'azure_pipeline/DigitalOcean-ContainerRegistry/koldste.dev'

  # release pipeline variables
  # - group: Container-Registry-do
- name: imagePullSecret
  value: azure-secret-registry-$(registryName)
- name: k8sNamespace
  value: backend
- name: containerRegistryURL
  value: 'registry.digitalocean.com'
- name: containerRegistryAPIBaseURL
  value: 'https://api.digitalocean.com/v2/registry/$(registryName)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build, push and publish artifact
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Build and push an image to container registry'
      inputs:
        containerRegistry: '$(containerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: '$(tag)'
        
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'Manifests'
        path: 'Koldste.dev.Web/Manifests'



# Release pipeline
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: ubuntu-latest
    environment: koldstedev-do-kubernetes
    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'Manifests'
              downloadPath: '$(System.ArtifactsDirectory)/Manifests'

          - task: KubernetesManifest@1
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'koldstedev-do-kubernetes-backend-1711399786755'
              namespace: '$(k8sNamespace)'
              secretType: 'dockerRegistry'
              secretName: '$(imagePullSecret)'
              dockerRegistryEndpoint: 'azure_pipeline/DigitalOcean-ContainerRegistry/koldste.dev'

          - script: |
              sed -i "s|{{DOCKER_IMAGE_NAME}}|$(containerRegistryURL)/$(imageRepository)|g" $(System.ArtifactsDirectory)/Manifests/website-koldstedev/Deployment_koldstedev.yaml
              sed -i "s|{{DOCKER_IMAGE_TAG}}|$(tag)|" $(System.ArtifactsDirectory)/Manifests/website-koldstedev/Deployment_koldstedev.yaml
            displayName: 'Replace Docker image name and tag in deployment manifest file'

          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'koldstedev-do-kubernetes-backend-1711399786755'
              namespace: '$(k8sNamespace)'
              manifests: |
                $(System.ArtifactsDirectory)/Manifests/website-koldstedev/Deployment_koldstedev.yaml
                $(System.ArtifactsDirectory)/Manifests/website-koldstedev/Service_koldstedev.yaml
              imagePullSecrets: '$(imagePullSecret)'
              rolloutStatusTimeout: '180'
          
          # - script: |
          #     sudo snap install doctl
          #   displayName: 'Installs latest version of doctl'


          # - task: DockerInstaller@0
          #   inputs:
          #     dockerVersion: '17.09.0-ce'

          - task: Bash@3
            displayName: 'Clean up the container registry'
            inputs:
              targetType: 'inline'
              arguments: '--delete_days_old 3 --min_to_keep 10 --verbose yes'
              script: |
                #!/bin/bash

                min_to_keep=${min_to_keep:-10}
                delete_days_old=${delete_days_old:-4}
                verbose=no
                repository=$(repositoryName)
                bearer_token_container_registry=$(bearerTokenContainerRegistry)
                container_registry_API_base_URL=$(containerRegistryAPIBaseURL)
                repository_name_URL_encoded=$(repositoryNameURLEncoded)
      
                # while [ $# -gt 0 ]; do
      
                #   if [[ $1 == *"--"* ]]; then
                #     param="${1/--/}"
                #     declare "$param"="$2"
                #   fi
      
                #   shift
                # done
      
                # [[ -z "$repository" ]] && {
                #   echo "Error: You need to define '--repository'"
                #   exit 1
                # }

                [[ -z "$bearer_token_container_registry" ]] && {
                  echo "Error: You need to define '--bearer_token_container_registry'"
                  exit 1
                }

                [[ -z "$container_registry_API_base_URL" ]] && {
                  echo "Error: You need to define '--container_registry_API_base_URL'"
                  exit 1
                }

                date_boundary=$(date -v-"$delete_days_old"d +%s)
                deletable_tags=$(curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer "$bearer_token_container_registry"" ""$container_registry_API_base_URL"/repositories/"$repository_name_URL_encoded"/tags?per_page=200" | jq ".tags[] | .[10:] | .[] | select ( .updated_at | fromdateiso8601 < $date_boundary) | .tag " -r | tr '\n' ' ')
      
                [[ -z "$deletable_tags" ]] && {
                  [[ "$verbose" == "yes" ]] && echo "Nothing to delete"
                  exit 0
                }
      
                [[ "$verbose" == "yes" ]] && {
                  echo "We are going to DELETE images that are more than $delete_days_old days"
                  echo "We are going to KEEP at least the newer $min_to_keep images"
      
                  echo "Deleteable tags: $deletable_tags"
                }

                for tag in $deletable_tags; do
                  curl -X DELETE -H "Content-Type: application/json" \
                    -H "Authorization: Bearer "$bearer_token_container_registry"" \
                    ""$container_registry_API_base_URL"/repositories/$repository_name_URL_encoded"/tags/$tag"
                done

                curl -X GET -H "Content-Type: application/json" \
                  -H "Authorization: Bearer "$bearer_token_container_registry"" \
                  ""$container_registry_API_base_URL"/registry/$repository_name_URL_encoded/garbage-collection"
              failOnStderr: true




          