### THIS PIPELINE RUNS SECOND AND AFTER THE "CI_.NET-azure-pipeline" PIPELINE ###
resources:

  repositories:
  - repository: repo
    type: git
    name: CV_Portfolio-Hjemmeside
    ref: main
    
  pipelines:
  - pipeline: CINETazurepipeline
    source: CI_.NET-azure-pipeline
    trigger: true

pool:
  vmImage: ubuntu-latest
container: mcr.microsoft.com/playwright/dotnet:v1.42.0-jammy

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.0.x'
  displayName: 'Use .NET SDK'

- script: dotnet build --configuration Release
  displayName: 'Build'
- script: dotnet test --configuration Release
  displayName: 'Run tests'