### THIS PIPELINE RUNS SECOND AND AFTER THE "CI_.NET-azure-pipeline" PIPELINE ###
trigger: none # Trigger is located at the bottom of this pipeline.

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.0.x'
  displayName: 'Use .NET SDK'
- script: dotnet build --configuration Release
  displayName: 'Build'
- script: pwsh Koldste.dev.Tests.Playwright/bin/Release/net8.0/playwright.ps1 install --with-deps
  displayName: 'Install Playwright browsers'
- script: dotnet test --configuration Release
  displayName: 'Run tests'

- script: |
    echo $(System.AccessToken) | az devops login

    az pipelines run --name CI_Docker-build-push-azure-pipeline --branch $(Build.SourceBranchName)

    az devops logout
        
  condition: succeeded()
  displayName: 'Trigger for CI_Docker-build-push-azure-pipeline'