### THIS PIPELINE RUNS THIRD AND AFTER THE "CI_Docker-build-push-azure-pipeline" PIPELINE ###
resources:

  repositories:
  - repository: repo
    type: git
    name: CV_Portfolio-Hjemmeside
    ref: self
    
  pipelines:
  - pipeline: CIDockerbuildpushazurepipeline
    source: CI_Docker-build-push-azure-pipeline
    trigger: true

pool:
  vmImage: ubuntu-latest
container: mcr.microsoft.com/playwright/dotnet:v1.41.2-jammy

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.0.x'
  displayName: 'Use .NET SDK'

- script: dotnet build --configuration Release
  displayName: 'Build'
- script: dotnet test --configuration Release
  displayName: 'Run tests'